# Generated by Django 5.0.1 on 2025-04-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0009_alter_propriedade_bairro_alter_propriedade_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='analise_matricula',
            field=models.TextField(blank=True, null=True, verbose_name='Análise da Matrícula'),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='matricula_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Matrícula'),
        ),
    ]
