# Generated by Django 5.2 on 2025-04-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propriedades', '0010_propriedade_analise_matricula_and_more'),
    ]

    operations = [
    ]
